title: Anusha Dixit
logo: https://github.com/Anusha1901/Anusha1901/blob/main/assets/IMG_20210329_182308_786.jpg
description: Aspiring Data Scientist
show_downloads: true
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
